"""description_of_changes

Revision ID: 26db5cb1f0af
Revises: 6565c80e18da
Create Date: 2024-03-14 21:54:24.505430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26db5cb1f0af'
down_revision: Union[str, None] = '6565c80e18da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routing_table', sa.Column('interface', sa.String(), nullable=True))
    op.drop_column('routing_table', 'interface_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routing_table', sa.Column('interface_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('routing_table', 'interface')
    # ### end Alembic commands ###
